service: thants

provider:
  name: aws
  runtime: python3.6
  stage: dev
  memorysize: 128
  region: eu-west-2

functions:
  string_transformer:
    handler: handler.string_transformer
    events:
      - http:
          path: string_transformer
          method: post
