service: thants

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: eu-west-2

functions:
  string_transformer:
    handler: handler.string_transformer
    events:
      - http: POST string_transformer
